### ISSUE TITLE
Allowing to fork

### ISSUE THREAD

**Issue by cmastalli** [iit-DLSLab/gym-quadruped#1]
Hi @Danfoa,

Thanks for sharing this repository. I will review it as soon as possible. However, it might be useful to allow others to fork the repository. 

As you might know, forking allows others to develop features on it without having access to write or push new branches. It also helps to avoid "pollution" with everyone's branch. For instance, in Crocoddyl, we keep two branches (main and devel) and strictly avoid others pushing their branches. More importantly, this also constrains everyone from merging new features without creating a PR. This is an appropriate way of developing, even for project admins.

Allowing to fork this repository is as simple as explained in https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/managing-the-forking-policy-for-your-repository#

Best,
Carlos

**Comment by Danfoa** [comment]
Ciao @cmastalli,

I think this was simply because the project was still private. I made it public now so it should be open to forks and PRs.

**Comment by cmastalli** [comment]
You don't need to make it public. I think we shouldn't make it public now.
