### ISSUE TITLE
Issue with self-collision with heightmap 

### ISSUE THREAD

**Issue by giulioturrisi** [iit-DLSLab/gym-quadruped#8]
This issue is related to the heightmap PR https://github.com/iit-DLSLab/gym-quadruped/pull/7

For now, self-collision is only disable for aliengo with an hack (we set the alpha value in the rgba to 0 for the feet), but should be disabled directly in the mj_ray function in heightmap.py using geomgroups or bodyexclude (see https://mujoco.readthedocs.io/en/latest/APIreference/APIfunctions.html)

**Comment by giulioturrisi** [comment]
Solved in https://github.com/iit-DLSLab/gym-quadruped/commit/a214bd2405ec2a4d56e0828a0923fa24a06fce63

**Comment by Danfoa** [comment]
Question wouldnt it be better to use visual geoms only for the heightmap? 

https://github.com/iit-DLSLab/gym-quadruped/blob/2596a4571e3ba14acc73fe900b0927efd11c85d6/gym_quadruped/utils/mujoco/visual.py#L95-L106

The last 3 lines ensures that the spheres are rendered, but not simulated, nor taken into account into segmentation, visual sensors, nor collision detection. 

Why do we need to hack the urdf?
